### PR TITLE
Feature/ctre lexer

### PR DESCRIPTION
**Pull request by antsouchlos**
- Removed `C++17` implementation of lexer, as the project has been upgraded to `C++20`.
  - Rewrote lexer using the `ctre` library

### CODE REVIEW

**Comment by antsouchlos** [comment]
Failed actions seem to be caused by outdated compilers not having proper `C++20` support.

Will wait for #31 to be merged (upgrade of `gcc` to `gcc11`) before merging this request.

**Comment by philsegeler** [comment]
I am really confused why your Windows cross build does not work, but mine does, although mine still does not work :D

Just tested your current state with all 3 compilers. You finally fixed the ```\"``` bug!!!!! Please also change all object/camera names on ```examples/oe_main_test.cpp``` to reflect that so I can move the camera around without warnings that it does not exist :)

And why did you set the buildtype to ```release``` instead of ```debugoptimized```?

**Comment by philsegeler** [comment]
Bug found, cannot correctly load ```OE_Demo2.csl``` and ```car_gma950.csl``` (press 2 or 4). Both display a black screen. I can load them both on the master branch.

I can still load ```monkeys.csl``` and ```OE_Demo50MB.csl``` correctly.

Bug is also found in emscripten and the windows build.

Btw you could also put ```cmake``` in the requirements, because it is needed to compile ```ctre```.

It is a blessing we have pull requests. I will try to see if i can find out through the renderer, but please also try to debug.

**Comment by antsouchlos** [comment]
After commit 714eb9a1296e8b995059a45d7f59592603d9bc62 `OE_Demo2.csl` is loaded successfully.

`car_gma950.csl` still throws an error (seems to be unrelated to the string quote thing though, as it is a `csl::unexpected_token_error_t`). Will investigate further.

**Comment by philsegeler** [comment]
```car_gma950.csl``` loads correctly for me, maybe you forgot to update the ```assets``` submodule?

**Review by philsegeler — APPROVED** [review]

**Pull request merged**
