### PR TITLE
Draft: Added github action to perform cross builds

### PR DESCRIPTION
**Pull request by antsouchlos**

### CODE REVIEW

**Comment by antsouchlos** [comment]
Jesus christ this is taking longer than I expected

**Comment by philsegeler** [comment]
Isn't emscripten available on ubuntu natively?

**Comment by antsouchlos** [comment]
`sudo apt-get install emscripten` didn't work. Not sure what kind of ubuntu version they are using. Also: It is apparently generally not recommended to use the `emscripten` version from the ubuntu repos, as that one seems to be quite outdated

**Comment by antsouchlos** [comment]
What exaclty is this error supposed to mean? (Happened on [this](https://github.com/antsouchlos/OxygenEngine2/runs/4754178465?check_suite_focus=true) action)

```
[37/39] Compiling C++ object libOxygenEngine.a.p/src_types_OE_World.cpp.o
em++: warning: linker setting ignored during compilation: 'WASM' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'EXPORT_ALL' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'USE_WEBGL2' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'SINGLE_FILE' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'FULL_ES3' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'NO_DISABLE_EXCEPTION_CATCHING' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'ALLOW_MEMORY_GROWTH' [-Wunused-command-line-argument]
em++: warning: linker setting ignored during compilation: 'PTHREAD_POOL_SIZE' [-Wunused-command-line-argument]
[38/39] Linking static target libOxygenEngine.a
[39/39] Linking target OE_Test.js
FAILED: OE_Test.js 
em++  -o OE_Test.js OE_Test.js.p/examples_oe_main_test.cpp.o -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXPORT_ALL=1 -s USE_SDL=2 -s USE_WEBGL2=1 -s SINGLE_FILE -s FULL_ES3=1 -s NO_DISABLE_EXCEPTION_CATCHING -s ALLOW_MEMORY_GROWTH=1 -s PTHREAD_POOL_SIZE=2 -s USE_PTHREADS=1 --preload-file=../assets@/assets -Wl,--start-group libOxygenEngine.a -Wl,--end-group -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4
em++: warning: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
Nothing to do!
em++: error: '/home/runner/emsdk/upstream/emscripten/tools/file_packager OE_Test.data --from-emcc --export-name=Module --preload ../assets@/assets' failed (returned 1)
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

**Comment by philsegeler** [comment]
FYI the `cross_web` script has to be run from the top level directory and not some random other directory.

`emscripten` also needs to package the .csl files in the `assets` directory else they won't be available.

**Comment by antsouchlos** [comment]
It needs access to the `*.csl` files? There is the problem. (Hadn't cloned the `assets` submodule)

**Comment by philsegeler** [comment]
Ah yes, i knew this was gonna happen.

**Comment by antsouchlos** [comment]
Any idea what [this](https://github.com/antsouchlos/OxygenEngine2/runs/4754208103?check_suite_focus=true) is about?

```
[208/213] Compiling C++ object libOxygenEngine.a.p/src_types_OE_World.cpp.obj
[209/213] Linking static target libOxygenEngine.a
[210/213] Compiling C++ object CSL_Test.exe.p/examples_csl_main_test.cpp.obj
[211/213] Compiling C++ object OE_Test.exe.p/examples_oe_main_test.cpp.obj
[212/213] Linking target CSL_Test.exe
[213/213] Linking target OE_Test.exe
cp: cannot stat '/usr/x86_64-w64-mingw32/bin/libwinpthread-1.dll': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by philsegeler** [comment]
You can comment out the last line on `cross_linux2windows` (but do not remove it).
What it does is copy the only needed .dll so one can package the engine easily. It was used for `share_oe.zip` before.

**Comment by philsegeler** [comment]
The path to the `.dll` was hardcoded for Arch Linux

**Comment by philsegeler** [comment]
Also a good idea would be to split the `cross_build` jobs into one for `emscripten` and one for windows.

**Comment by antsouchlos** [comment]
That might be a good idea. The reason I have not split them yet, is because I am not entirely sure which option would run faster. Splitting them into two different jobs would basically require another ubuntu installation with required compilers, libraries, etc. to be created. But running them in parallel might speed it up actually. Will test in a new commit

**Review by philsegeler — APPROVED** [review]

**Comment by antsouchlos** [comment]
Separate jobs are faster, keeping the commit

**Pull request merged**
