### PR TITLE
Feature/examples folder

### PR DESCRIPTION
**Pull request by antsouchlos**
Moved source files from repo root directory into dedicated `examples` folder

### CODE REVIEW

**Review by philsegeler — CHANGES_REQUESTED** [review]
You will need to change the files themselves, so that they can load from the assets directory

**Comment by philsegeler** [comment]
Or maybe not. Do they run correctly?

**Comment by antsouchlos** [comment]
Compilation itself works, `OE_Test` seems to run correctly

**Comment by philsegeler** [comment]
Yeah, my brain though that if we change the `.cpp` position that the root directory changes, but it is only important where the **execution** happens and not where the `.cpp` is. :P

**Review by philsegeler — APPROVED** [review]

**Pull request merged**
